name: Update

on:
  schedule:
    - cron:  '17 5 1 * *'

  workflow_dispatch:

jobs:
  update:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      - uses: denoland/setup-deno@v1

      - name: update
        run: deno task update

      - name: git setting
        run: |
          git config --local user.email "${GITHUB_ACTOR}@users.noreply.github.com"
          git config --local user.name "${GITHUB_ACTOR}"

      - name: Git push
        run: |
          git add .
          git commit -m "Update holiday." | true
          git push | true
